# Generated by Django 3.1.7 on 2021-03-03 02:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seekrapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployerProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_img', models.CharField(max_length=200)),
                ('user', models.OneToOneField(default=3, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_description', models.TextField()),
                ('salary', models.IntegerField()),
                ('benefits', models.BooleanField()),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seekrapi.employerprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Languages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='SeekerProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(max_length=350)),
                ('profile_img', models.CharField(max_length=200)),
                ('project_name', models.CharField(max_length=200)),
                ('project_detail', models.TextField(max_length=300)),
                ('project_img', models.CharField(max_length=200)),
                ('github_username', models.CharField(max_length=200)),
                ('tech_ed', models.CharField(max_length=200)),
                ('experience', models.IntegerField()),
                ('work_history', models.CharField(blank=True, max_length=200)),
                ('languages', models.ManyToManyField(related_name='seeker_languages', related_query_name='seeker_language', to='seekrapi.Languages')),
                ('user', models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SeekerAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seeker_response', models.BooleanField()),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seekrapi.jobposting')),
                ('seeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seekrapi.seekerprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seekrapi.employerprofile')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seekrapi.jobposting')),
                ('seeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seekrapi.seekerprofile')),
            ],
        ),
        migrations.CreateModel(
            name='EmployerAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employer_response', models.BooleanField()),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seekrapi.jobposting')),
                ('seeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seekrapi.seekerprofile')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=30)),
                ('company_bio', models.TextField()),
                ('company_logo', models.CharField(max_length=200)),
                ('employer_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seekrapi.employerprofile')),
            ],
        ),
    ]
