# Generated by Django 3.1.7 on 2021-03-11 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seekrapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='job_title',
            field=models.CharField(default=2, max_length=250),
            preserve_default=False,
        ),
    ]
