# Generated by Django 3.1.7 on 2021-03-04 00:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seekrapi', '0002_companyprofile_employeraction_employerprofile_jobposting_languages_match_seekeraction_seekerprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='employer',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='seekrapi.employerprofile'),
        ),
        migrations.AlterField(
            model_name='match',
            name='seeker',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='seekrapi.seekerprofile'),
        ),
        migrations.AlterField(
            model_name='seekerprofile',
            name='project_detail',
            field=models.TextField(max_length=400),
        ),
    ]
