# Generated by Django 3.1.7 on 2021-03-15 23:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seekrapi', '0002_remove_employeraction_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeraction',
            name='job',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='seekrapi.jobposting'),
            preserve_default=False,
        ),
    ]
