# Generated by Django 3.1.7 on 2021-03-04 00:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seekrapi', '0003_auto_20210304_0019'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeraction',
            name='employer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='seekrapi.employerprofile'),
            preserve_default=False,
        ),
    ]
