# Generated by Django 3.1.7 on 2021-03-04 00:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seekrapi', '0004_employeraction_employer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='employer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='seekrapi.employerprofile'),
        ),
        migrations.AlterField(
            model_name='match',
            name='seeker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='seekrapi.seekerprofile'),
        ),
    ]
